[package]
name = "rigidbod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.12.2"
nalgebra-glm = "0.18.0"
slint = "1.0.2"
vulkano-shaders = "0.33.0"
